In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##Vocabulary size
voc_size=10000

# One hot representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
onehot_repr

[[1368, 4042, 3134, 3442],
 [1368, 4042, 3134, 7872],
 [1368, 7137, 3134, 7954],
 [3067, 1318, 8156, 7946, 3393],
 [3067, 1318, 8156, 7946, 5539],
 [1326, 1368, 6850, 3134, 1019],
 [3122, 4881, 2071, 7946]]

# word Embedding

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1368 4042 3134 3442]
 [   0    0    0    0 1368 4042 3134 7872]
 [   0    0    0    0 1368 7137 3134 7954]
 [   0    0    0 3067 1318 8156 7946 3393]
 [   0    0    0 3067 1318 8156 7946 5539]
 [   0    0    0 1326 1368 6850 3134 1019]
 [   0    0    0    0 3122 4881 2071 7946]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985
    0.03241489 -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
  [-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985
    0.03241489 -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
  [-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985
    0.03241489 -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
  [-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985
    0.03241489 -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
  [-0.0337588   0.02574302 -0.0301854   0.02004006  0.0307009
   -0.03018256 -0.0312848   0.00141791 -0.01638544 -0.03146945]
  [ 0.00860897  0.03820392 -0.0041785  -0.02540771 -0.0215348
    0.04231408 -0.00683541 -0.02068937  0.01845247  0.03570582]
  [-0.03876812  0.043935    0.02725524  0.01407405 -0.02392055
   -0.04217824  0.00275106  0.02397429 -0.04735185 -0.01393135]
  [-0.00386352  0.03984884  0.01252984  0.02362524 -0.04360155
    0.01187747 -0.04763836 -0.01903543  0.02290738

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 1368, 4042, 3134, 3442])

In [17]:
print(model.predict(embedded_docs)[0])

[[-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985  0.03241489
  -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
 [-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985  0.03241489
  -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
 [-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985  0.03241489
  -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
 [-0.03574183 -0.01863484  0.03578306  0.01791468  0.01661985  0.03241489
  -0.01799039 -0.01416037 -0.01438429  0.0295676 ]
 [-0.0337588   0.02574302 -0.0301854   0.02004006  0.0307009  -0.03018256
  -0.0312848   0.00141791 -0.01638544 -0.03146945]
 [ 0.00860897  0.03820392 -0.0041785  -0.02540771 -0.0215348   0.04231408
  -0.00683541 -0.02068937  0.01845247  0.03570582]
 [-0.03876812  0.043935    0.02725524  0.01407405 -0.02392055 -0.04217824
   0.00275106  0.02397429 -0.04735185 -0.01393135]
 [-0.00386352  0.03984884  0.01252984  0.02362524 -0.04360155  0.01187747
  -0.04763836 -0.01903543  0.02290738  0.02532667]]